"""added total_reviews field to Listing table

Revision ID: 143e7fe5a07c
Revises: 579b2a7f28f3
Create Date: 2025-08-26 03:05:45.258938

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '143e7fe5a07c'
down_revision: Union[str, Sequence[str], None] = '579b2a7f28f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('total_reviews', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'total_reviews')
    # ### end Alembic commands ###
