"""added Booking table

Revision ID: 3c4237309800
Revises: 70900cee646a
Create Date: 2025-08-26 19:23:12.638443

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3c4237309800'
down_revision: Union[str, Sequence[str], None] = '70900cee646a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('check_in_date', sa.Date(), nullable=False),
                    sa.Column('check_out_date', sa.Date(), nullable=False),
                    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
                    sa.Column('status',
                              sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'FAILED', name='bookingstatus'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('listing_id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_bookings_listing_id'), 'bookings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.add_column('apartments', sa.Column('min_lease_months', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'min_lease_months')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_listing_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
