"""added is_thumbnail field to Image table

Revision ID: 579b2a7f28f3
Revises: d6529fa85293
Create Date: 2025-08-26 02:04:47.944979

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '579b2a7f28f3'
down_revision: Union[str, Sequence[str], None] = 'd6529fa85293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_thumbnail', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_thumbnail')
    # ### end Alembic commands ###
