"""Create initial data models for listings, amenities, images, and reviews

Revision ID: 67fe13f367d7
Revises: 6a3b8f8d38f5
Create Date: 2025-08-25 09:02:06.715050

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '67fe13f367d7'
down_revision: Union[str, Sequence[str], None] = '6a3b8f8d38f5'
branch_labels: Union[str, Sequence[str], None] = None

listing_type_enum = sa.Enum('HOTEL', 'HOSTEL', 'APARTMENT', 'GUESTHOUSE', name='listingtype')
pricing_unit_enum = sa.Enum('PER_NIGHT', 'PER_MONTH', 'PER_YEAR', name='pricingunit')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    listing_type_enum.create(op.get_bind(), checkfirst=False)
    pricing_unit_enum.create(op.get_bind(), checkfirst=False)
    op.create_table('images',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('url', sa.String(length=2048), nullable=False),
                    sa.Column('listing_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_images_listing_id'), 'images', ['listing_id'], unique=False)
    op.create_table('reviews',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('comment', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('listing_id', sa.UUID(), nullable=False),
                    sa.Column('reviewer_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
                    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_reviews_listing_id'), 'reviews', ['listing_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.drop_column('guesthouses', 'is_breakfast_included')
    op.add_column('listings', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('listings', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('listings', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('listings', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('listings', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('listings', sa.Column('price_unit', pricing_unit_enum, nullable=False))
    op.add_column('listings', sa.Column('currency', sa.String(length=3), nullable=False))
    op.alter_column('listings', 'type',
                    existing_type=sa.VARCHAR(length=50),
                    type_=listing_type_enum,
                    existing_nullable=False,
                    postgresql_using="type::listingtype")
    op.create_index(op.f('ix_listings_city'), 'listings', ['city'], unique=False)
    op.drop_column('listings', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_listings_city'), table_name='listings')
    op.alter_column('listings', 'type',
                    existing_type=listing_type_enum,
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=False)
    op.drop_column('listings', 'currency')
    op.drop_column('listings', 'price_unit')
    op.drop_column('listings', 'price')
    op.drop_column('listings', 'longitude')
    op.drop_column('listings', 'latitude')
    op.drop_column('listings', 'city')
    op.drop_column('listings', 'address')
    op.add_column('guesthouses', sa.Column('is_breakfast_included', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_listing_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_images_listing_id'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
