"""Add joined-table inheritance for listings

Revision ID: 6a3b8f8d38f5
Revises: f20d08ad82a4
Create Date: 2025-08-25 08:16:52.185035

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a3b8f8d38f5'
down_revision: Union[str, Sequence[str], None] = 'f20d08ad82a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('guesthouses',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('number_of_rooms', sa.Integer(), nullable=False),
                    sa.Column('is_breakfast_included', sa.Boolean(), nullable=False),
                    sa.Column('host_on_site', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['listings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('listing_amenities',
                    sa.Column('listing_id', sa.UUID(), nullable=False),
                    sa.Column('amenity_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
                    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
                    sa.PrimaryKeyConstraint('listing_id', 'amenity_id')
                    )
    op.add_column('apartments', sa.Column('max_guests', sa.Integer(), nullable=False))
    op.drop_column('apartments', 'has_kitchen')
    op.drop_column('hostels', 'lockers_available')
    op.drop_column('hotels', 'amenities')
    op.add_column('listings', sa.Column('average_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'average_rating')
    op.add_column('hotels',
                  sa.Column('amenities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('lockers_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('apartments', sa.Column('has_kitchen', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('apartments', 'max_guests')
    op.drop_table('listing_amenities')
    op.drop_table('guesthouses')
    op.drop_table('amenities')
    # ### end Alembic commands ###
