"""added profile_picture_public_id to User table

Revision ID: 70900cee646a
Revises: e14dc74ecf8b
Create Date: 2025-08-26 16:58:02.431359

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '70900cee646a'
down_revision: Union[str, Sequence[str], None] = 'e14dc74ecf8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_public_id')
    # ### end Alembic commands ###
