"""added date_of_birth and profile_picture_url fields to user model

Revision ID: 9f8d67012276
Revises: c18a3c048048
Create Date: 2025-08-25 06:50:58.859677

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f8d67012276'
down_revision: Union[str, Sequence[str], None] = 'c18a3c048048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=2048), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
