"""added icon_url field to amenites table

Revision ID: d6529fa85293
Revises: bbc6e1db206f
Create Date: 2025-08-25 23:40:17.932146

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd6529fa85293'
down_revision: Union[str, Sequence[str], None] = 'bbc6e1db206f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amenities', sa.Column('icon_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amenities', 'icon_url')
    # ### end Alembic commands ###
