"""added public_id field to Image table

Revision ID: e14dc74ecf8b
Revises: 143e7fe5a07c
Create Date: 2025-08-26 16:01:50.841973

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e14dc74ecf8b'
down_revision: Union[str, Sequence[str], None] = '143e7fe5a07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('public_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'images', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_column('images', 'public_id')
    # ### end Alembic commands ###
