"""added type field to Booking table

Revision ID: e5fa862bdf34
Revises: 3c4237309800
Create Date: 2025-08-26 20:00:17.559119

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e5fa862bdf34'
down_revision: Union[str, Sequence[str], None] = '3c4237309800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'type')
    # ### end Alembic commands ###
