"""Add joined-table inheritance for listings

Revision ID: f20d08ad82a4
Revises: 9f8d67012276
Create Date: 2025-08-25 07:44:41.747890

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f20d08ad82a4'
down_revision: Union[str, Sequence[str], None] = '9f8d67012276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('location', sa.String(length=255), nullable=False),
                    sa.Column('owner_id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(length=50), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_listings_owner_id'), 'listings', ['owner_id'], unique=False)
    op.create_table('apartments',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('number_of_bedrooms', sa.Integer(), nullable=False),
                    sa.Column('number_of_bathrooms', sa.Integer(), nullable=False),
                    sa.Column('has_kitchen', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['listings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('hostels',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('dorm_bed_count', sa.Integer(), nullable=True),
                    sa.Column('private_room_count', sa.Integer(), nullable=True),
                    sa.Column('lockers_available', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['listings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('hotels',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('star_rating', sa.Integer(), nullable=False),
                    sa.Column('amenities', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['listings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotels')
    op.drop_table('hostels')
    op.drop_table('apartments')
    op.drop_index(op.f('ix_listings_owner_id'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
